package registro.eingv.uabc.registroeingv.dbA;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**

 * Entity mapped to table ALARMA.
 */
import java.io.Serializable;

public class Alarma implements Serializable{

    private Integer _id;
    private String tituloAlarma;
    private java.util.Date horaDeAlarma;

    public Alarma() {
    }

    public Alarma(Integer _id) {
        this._id = _id;
    }

    public Alarma(Integer _id, String tituloAlarma, java.util.Date horaDeAlarma) {
        this._id = _id;
        this.tituloAlarma = tituloAlarma;
        this.horaDeAlarma = horaDeAlarma;
    }

    public Integer get_id() {
        return _id;
    }

    public void set_id(Integer _id) {
        this._id = _id;
    }

    public String getTituloAlarma() {
        return tituloAlarma;
    }

    public void setTituloAlarma(String tituloAlarma) {
        this.tituloAlarma = tituloAlarma;
    }

    public java.util.Date getHoraDeAlarma() {
        return horaDeAlarma;
    }

    public void setHoraDeAlarma(java.util.Date horaDeAlarma) {
        this.horaDeAlarma = horaDeAlarma;
    }

}
