package registro.eingv.uabc.registroeingv.dbA;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig alarmaDaoConfig;

    private final AlarmaDao alarmaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        alarmaDaoConfig = daoConfigMap.get(AlarmaDao.class).clone();
        alarmaDaoConfig.initIdentityScope(type);


        alarmaDao = new AlarmaDao(alarmaDaoConfig, this);

        registerDao(Alarma.class, alarmaDao);
    }
    
    public void clear() {
        alarmaDaoConfig.getIdentityScope().clear();
    }

    public AlarmaDao getAlarmaDao() {
        return alarmaDao;
    }


}
